### ISSUE TITLE
ExecAnalyzer Out of Memory Exception.

### ISSUE THREAD

**Issue by junghuk** [spideruci/tacoco#7]
I ran analyzer for 2 projects. 
One with 86 test cases works fine. 
One with 3646 test cases throws OOM.

It took 21min until OOM. 
Memory stat: Final Memory: 9M/949M
When OOM is thrown, there is no json output.

This is call stack.
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
    at org.jacoco.core.internal.analysis.SourceNodeImpl.ensureCapacity(SourceNodeImpl.java:65)
    at org.jacoco.core.internal.analysis.SourceNodeImpl.increment(SourceNodeImpl.java:93)
    at org.jacoco.core.internal.analysis.ClassCoverageImpl.addMethod(ClassCoverageImpl.java:71)
    at org.jacoco.core.internal.analysis.ClassAnalyzer$1.visitEnd(ClassAnalyzer.java:96)
    at org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:877)
    at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:836)
    at org.jacoco.core.internal.flow.ClassProbesAdapter$2.visitEnd(ClassProbesAdapter.java:89)
    at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1021)
    at org.objectweb.asm.ClassReader.accept(ClassReader.java:693)
    at org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
    at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:107)
    at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:142)
    at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:175)
    at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:208)
    at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:203)
    at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:203)
    at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:203)
    at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:203)
    at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:203)
    at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:203)
    at org.spideruci.tacoco.reporting.ExecutionDataParser.analyzeStructure(ExecutionDataParser.java:78)
    at org.spideruci.tacoco.reporting.ExecutionDataParser.resetExecDataStore(ExecutionDataParser.java:55)
    at org.spideruci.tacoco.reporting.ExecAnalyzer$1.visitSessionInfo(ExecAnalyzer.java:71)
    at org.jacoco.core.data.ExecutionDataReader.readSessionInfo(ExecutionDataReader.java:139)
    at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:110)
    at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:87)
    at org.spideruci.tacoco.reporting.ExecAnalyzer.dumpContent(ExecAnalyzer.java:78)
    at org.spideruci.tacoco.reporting.ExecAnalyzer.main(ExecAnalyzer.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)

**Comment by VijayKrishna** [comment]
@junghuk take it for another spin. If you still see an issue, please let me know -- and this time also send me your jacoco.exec and your project directory in a zip file. Thanks!

**Comment by junghuk** [comment]
It works without OOM now. Good job!
I'll close this issue.
